export const mockGsms: Master.GsmItem[] = [
  {
    gsmId: 1,
    name: "Cover Paper 200 GSM",
    localName: "कवर पेपर 200 GSM",
    gsmValue: 200,
    usage: "Cover",
    code: "IS-1848",
    isActive: true,
  },
  {
    gsmId: 2,
    name: "Maplitho 70 GSM",
    localName: "मैपलिथो 70 GSM",
    gsmValue: 70,
    usage: "Printing",
    code: "IS-1848",
    isActive: true,
  },
  {
    gsmId: 3,
    name: "Printing Paper 58 GSM",
    localName: "मुद्रण पेपर 58 GSM",
    gsmValue: 58,
    usage: "Printing",
    code: "IS-1848",
    isActive: true,
  },
  {
    gsmId: 4,
    name: "Printing Paper 60 GSM",
    localName: "मुद्रण पेपर 60 GSM",
    gsmValue: 60,
    usage: "Printing",
    code: "IS-1848",
    isActive: true,
  },
  {
    gsmId: 5,
    name: "Cover Paper 170 GSM",
    localName: "कवर पेपर 170 GSM",
    gsmValue: 170,
    usage: "Cover",
    code: "IS-1848",
    isActive: true,
  },
];
