export const mockDemandApprovals: Distribution.DemandApprovalItem[] = [
  {
    id: 1,
    agencyName: "CPI",
    district: "RSK - Bhopal",
    titleName: "पाठ्यपुस्तक / एकाउंटेन्सी (Part 1)",
    bookType: "पाठ्यपुस्तक",
    classGroup: "High School 9-12",
    medium: "Hindi",
    requestedDemand: 164550,
    currentStock: 124,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 2,
    agencyName: "CPI",
    district: "RSK - Bhopal",
    titleName: "पाठ्यपुस्तक / एटग्रेड - 12 (गणित)",
    bookType: "पाठ्यपुस्तक",
    classGroup: "High School 9-12",
    medium: "Hindi",
    requestedDemand: 177550,
    currentStock: 75,
    variance: "-0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 3,
    agencyName: "CPI",
    district: "RSK - Bhopal",
    titleName: "सहायक वाचन - 10",
    bookType: "पाठ्यपुस्तक",
    classGroup: "High School 9-12",
    medium: "Hindi",
    requestedDemand: 181000,
    currentStock: 30,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 4,
    agencyName: "CPI",
    district: "District Aggregation",
    titleName: "इंग्लिश रीडर जनरल सीरीज - 9",
    bookType: "पाठ्यपुस्तक",
    classGroup: "High School 9-12",
    medium: "Hindi",
    requestedDemand: 107950,
    currentStock: 39,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 5,
    agencyName: "CPI",
    district: "RSK - Bhopal",
    titleName: "गणित - 11",
    bookType: "पाठ्यपुस्तक",
    classGroup: "High School 9-12",
    medium: "Hindi",
    requestedDemand: 107950,
    currentStock: 50,
    variance: "0.8%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 6,
    agencyName: "RSK",
    district: "RSK - Bhopal",
    titleName: "सामाजिक विज्ञान - 7",
    bookType: "पाठ्यपुस्तक",
    classGroup: "Classes 1-8",
    medium: "Hindi",
    requestedDemand: 206350,
    currentStock: 204,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 7,
    agencyName: "RSK",
    district: "District Aggregation",
    titleName: "संस्कृत भारती - 6",
    bookType: "पाठ्यपुस्तक",
    classGroup: "Classes 1-8",
    medium: "Hindi",
    requestedDemand: 214800,
    currentStock: 9,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 8,
    agencyName: "RSK",
    district: "District Aggregation",
    titleName: "संस्कृत भारती - 5",
    bookType: "एटग्रेड",
    classGroup: "Classes 1-8",
    medium: "Hindi",
    requestedDemand: 223250,
    currentStock: 124,
    variance: "0.2%",
    status: "Pending",
    academicYear: "2026-2027",
  },
];
