// Milestone type definition
export interface Milestone {
  id: number;
  name: string;
  description: string;
  deadlineDate: string;
  dayOfWeek: string;
  completionDate: string;
  daysDiffText: string;
  daysDiffType: "early" | "late" | "remaining" | "on-time" | "overdue";
  scheduleStatus: "On Time" | "In Progress" | "Upcoming" | "Overdue";
  completionStatus: "Complete" | "Pending";
  progress: number;
}

// Demand Cycle type definition
export interface DemandCycle {
  id: string;
  name: string;
  periodText: string;
  status: "Active" | "Upcoming" | "Completed";
  statusText: string;
}

// Demand cycles definition
export const DEMAND_CYCLES: DemandCycle[] = [
  {
    id: "cycle-1",
    name: "Production Period (Jan 2026)",
    periodText: "05 Jan 2026 - 02 Apr 2026",
    status: "Completed",
    statusText: "Completed",
  },
  {
    id: "cycle-2",
    name: "Production Period (Jul 2026)",
    periodText: "05 Jul 2026 - 31 Oct 2026",
    status: "Active",
    statusText: "Active",
  },
  {
    id: "cycle-3",
    name: "Production Period (Jan 2027)",
    periodText: "05 Jan 2027 - 05 Apr 2027",
    status: "Upcoming",
    statusText: "Upcoming",
  },
];

// Milestones data based on cycle selection
export const ALL_MILESTONES: Record<string, Milestone[]> = {
  "cycle-1": [
    {
      id: 1,
      name: "Demand Submission (Books)",
      description:
        "Last date for submitting book demand from DPI/RSK departments",
      deadlineDate: "05 Jan 2026",
      dayOfWeek: "Monday",
      completionDate: "03 Jan 2026",
      daysDiffText: "+2 Days Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 2,
      name: "Demand Approval",
      description: "Approval of submitted book demand by DPI head office",
      deadlineDate: "15 Jan 2026",
      dayOfWeek: "Thursday",
      completionDate: "14 Jan 2026",
      daysDiffText: "+1 Day Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 3,
      name: "Paper Tender",
      description: "Tender process and vendor selection for paper procurement",
      deadlineDate: "25 Jan 2026",
      dayOfWeek: "Sunday",
      completionDate: "25 Jan 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 4,
      name: "Printer Tender",
      description: "Tender process for printing work and press selection",
      deadlineDate: "05 Feb 2026",
      dayOfWeek: "Thursday",
      completionDate: "08 Feb 2026",
      daysDiffText: "3 Days Overdue",
      daysDiffType: "late",
      scheduleStatus: "Overdue",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 5,
      name: "Paper Work Allocation",
      description: "Allocation of paper supply work orders to selected vendors",
      deadlineDate: "15 Feb 2026",
      dayOfWeek: "Sunday",
      completionDate: "15 Feb 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 6,
      name: "Printer Work Allocation",
      description: "Allocation of printing work to selected press operators",
      deadlineDate: "22 Feb 2026",
      dayOfWeek: "Sunday",
      completionDate: "22 Feb 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 7,
      name: "Paper Distribution to Central Depot",
      description:
        "Dispatch and delivery of paper rolls from vendor to central depot",
      deadlineDate: "05 Mar 2026",
      dayOfWeek: "Thursday",
      completionDate: "04 Mar 2026",
      daysDiffText: "+1 Day Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 8,
      name: "Lab Testing (Paper)",
      description:
        "Quality inspection and testing of paper GSM and strength at certified laboratories",
      deadlineDate: "09 Mar 2026",
      dayOfWeek: "Monday",
      completionDate: "09 Mar 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 9,
      name: "Central Depot to Printer (Paper)",
      description:
        "Dispatch of raw paper from central depot to assigned printers",
      deadlineDate: "12 Mar 2026",
      dayOfWeek: "Thursday",
      completionDate: "12 Mar 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 10,
      name: "Printer to Depot (Books)",
      description:
        "Delivery of printed textbooks from press back to regional depots",
      deadlineDate: "22 Mar 2026",
      dayOfWeek: "Sunday",
      completionDate: "20 Mar 2026",
      daysDiffText: "+2 Days Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 11,
      name: "Depot to Block Distribution (Books)",
      description:
        "Distribution of textbooks from regional depots to block resource centers (BRCs)",
      deadlineDate: "28 Mar 2026",
      dayOfWeek: "Saturday",
      completionDate: "28 Mar 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
  ],
  "cycle-2": [
    {
      id: 1,
      name: "Demand Submission (Books)",
      description:
        "Last date for submitting book demand from WCD/RSK departments",
      deadlineDate: "05 Jul 2026",
      dayOfWeek: "Sunday",
      completionDate: "03 Jul 2026",
      daysDiffText: "+2 Days Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 2,
      name: "Demand Approval",
      description: "Approval of submitted book demand by DPI head office",
      deadlineDate: "15 Jul 2026",
      dayOfWeek: "Wednesday",
      completionDate: "15 Jul 2026",
      daysDiffText: "Completed on Time",
      daysDiffType: "on-time",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 3,
      name: "Paper Tender",
      description: "Tender process and vendor selection for paper procurement",
      deadlineDate: "30 Jul 2026",
      dayOfWeek: "Thursday",
      completionDate: "29 Jul 2026",
      daysDiffText: "+1 Day Early",
      daysDiffType: "early",
      scheduleStatus: "On Time",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 4,
      name: "Printer Tender",
      description: "Tender process for printing work and press selection",
      deadlineDate: "15 Aug 2026",
      dayOfWeek: "Saturday",
      completionDate: "16 Aug 2026",
      daysDiffText: "1 Day Overdue",
      daysDiffType: "late",
      scheduleStatus: "Overdue",
      completionStatus: "Complete",
      progress: 100,
    },
    {
      id: 5,
      name: "Paper Work Allocation",
      description: "Allocation of paper supply work orders to selected vendors",
      deadlineDate: "18 Aug 2026",
      dayOfWeek: "Tuesday",
      completionDate: "-",
      daysDiffText: "3 Days Overdue",
      daysDiffType: "overdue",
      scheduleStatus: "Overdue",
      completionStatus: "Pending",
      progress: 80,
    },
    {
      id: 6,
      name: "Printer Work Allocation",
      description: "Allocation of printing work to selected press operators",
      deadlineDate: "02 Sep 2026",
      dayOfWeek: "Wednesday",
      completionDate: "-",
      daysDiffText: "12 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "In Progress",
      completionStatus: "Pending",
      progress: 25,
    },
    {
      id: 7,
      name: "Paper Distribution to Central Depot",
      description:
        "Dispatch and delivery of paper rolls from vendor to central depot",
      deadlineDate: "15 Sep 2026",
      dayOfWeek: "Tuesday",
      completionDate: "-",
      daysDiffText: "25 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 8,
      name: "Lab Testing (Paper)",
      description:
        "Quality inspection and testing of paper GSM and strength at certified laboratories",
      deadlineDate: "20 Sep 2026",
      dayOfWeek: "Sunday",
      completionDate: "-",
      daysDiffText: "30 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 9,
      name: "Central Depot to Printer (Paper)",
      description:
        "Dispatch of raw paper from central depot to assigned printers",
      deadlineDate: "25 Sep 2026",
      dayOfWeek: "Friday",
      completionDate: "-",
      daysDiffText: "35 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 10,
      name: "Printer to Depot (Books)",
      description:
        "Delivery of printed textbooks from press back to regional depots",
      deadlineDate: "12 Oct 2026",
      dayOfWeek: "Monday",
      completionDate: "-",
      daysDiffText: "52 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 11,
      name: "Depot to Block Distribution (Books)",
      description:
        "Distribution of textbooks from regional depots to block resource centers (BRCs)",
      deadlineDate: "22 Oct 2026",
      dayOfWeek: "Thursday",
      completionDate: "-",
      daysDiffText: "62 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
  ],
  "cycle-3": [
    {
      id: 1,
      name: "Demand Submission (Books)",
      description:
        "Last date for submitting book demand from WCD/RSK departments",
      deadlineDate: "05 Jan 2027",
      dayOfWeek: "Tuesday",
      completionDate: "-",
      daysDiffText: "137 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 2,
      name: "Demand Approval",
      description: "Approval of submitted book demand by DPI head office",
      deadlineDate: "15 Jan 2027",
      dayOfWeek: "Friday",
      completionDate: "-",
      daysDiffText: "147 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 3,
      name: "Paper Tender",
      description: "Tender process and vendor selection for paper procurement",
      deadlineDate: "25 Jan 2027",
      dayOfWeek: "Monday",
      completionDate: "-",
      daysDiffText: "157 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 4,
      name: "Printer Tender",
      description: "Tender process for printing work and press selection",
      deadlineDate: "05 Feb 2027",
      dayOfWeek: "Friday",
      completionDate: "-",
      daysDiffText: "168 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 5,
      name: "Paper Work Allocation",
      description: "Allocation of paper supply work orders to selected vendors",
      deadlineDate: "15 Feb 2027",
      dayOfWeek: "Monday",
      completionDate: "-",
      daysDiffText: "178 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 6,
      name: "Printer Work Allocation",
      description: "Allocation of printing work to selected press operators",
      deadlineDate: "22 Feb 2027",
      dayOfWeek: "Monday",
      completionDate: "-",
      daysDiffText: "185 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 7,
      name: "Paper Distribution to Central Depot",
      description:
        "Dispatch and delivery of paper rolls from vendor to central depot",
      deadlineDate: "05 Mar 2027",
      dayOfWeek: "Friday",
      completionDate: "-",
      daysDiffText: "196 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 8,
      name: "Lab Testing (Paper)",
      description:
        "Quality inspection and testing of paper GSM and strength at certified laboratories",
      deadlineDate: "09 Mar 2027",
      dayOfWeek: "Tuesday",
      completionDate: "-",
      daysDiffText: "200 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 9,
      name: "Central Depot to Printer (Paper)",
      description:
        "Dispatch of raw paper from central depot to assigned printers",
      deadlineDate: "12 Mar 2027",
      dayOfWeek: "Friday",
      completionDate: "-",
      daysDiffText: "203 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 10,
      name: "Printer to Depot (Books)",
      description:
        "Delivery of printed textbooks from press back to regional depots",
      deadlineDate: "22 Mar 2027",
      dayOfWeek: "Monday",
      completionDate: "-",
      daysDiffText: "213 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
    {
      id: 11,
      name: "Depot to Block Distribution (Books)",
      description:
        "Distribution of textbooks from regional depots to block resource centers (BRCs)",
      deadlineDate: "28 Mar 2027",
      dayOfWeek: "Sunday",
      completionDate: "-",
      daysDiffText: "219 Days Remaining",
      daysDiffType: "remaining",
      scheduleStatus: "Upcoming",
      completionStatus: "Pending",
      progress: 0,
    },
  ],
};
