export const mockTitleApprovals: Distribution.TitleApprovalItem[] = [
  {
    id: 1,
    titleCode: "TTL-2026-081",
    titleName: "Textbook / Atgrade - 8 (Maths)",
    localTitleName: "पाठ्यपुस्तक / एटग्रेड - 8 (गणित)",
    department: "RSK",
    className: "Class 8",
    medium: "Hindi Medium",
    bookType: "Atgrade Workbook",
    innerPages: 100,
    coverPages: 4,
    totalPages: 104,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 220,
    paperArea: 2.1,
    matterDocumentUrl: "/uploads/TTL-2026-081_Maths_Class8_RSK.pdf",
    receivedDate: "2026-10-15",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 2,
    titleCode: "TTL-2026-092",
    titleName: "Textbook / Accountancy - 12 (Part 1)",
    localTitleName: "पाठ्यपुस्तक / एकाउंटेन्सी - 12 (भाग 1)",
    department: "CPI",
    className: "Class 12",
    medium: "Hindi Medium",
    bookType: "Main Textbook",
    innerPages: 140,
    coverPages: 4,
    totalPages: 144,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 310,
    paperArea: 3.2,
    matterDocumentUrl: "/uploads/TTL-2026-092_Accountancy_Class12_CPI.pdf",
    receivedDate: "2026-10-18",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 3,
    titleCode: "TTL-2026-095",
    titleName: "Supplementary Reader - 12",
    localTitleName: "सहायक वाचन - 12",
    department: "CPI",
    className: "Class 12",
    medium: "English Medium",
    bookType: "Supplementary Reader",
    innerPages: 92,
    coverPages: 4,
    totalPages: 96,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 190,
    paperArea: 1.8,
    matterDocumentUrl: "/uploads/TTL-2026-095_Reader_Class12_CPI.pdf",
    receivedDate: "2026-10-20",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 4,
    titleCode: "TTL-2026-084",
    titleName: "English Reader General Series - 8",
    localTitleName: "इंग्लिश रीडर जनरल सीरीज - 8",
    department: "RSK",
    className: "Class 8",
    medium: "English Medium",
    bookType: "Main Textbook",
    innerPages: 116,
    coverPages: 4,
    totalPages: 120,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 240,
    paperArea: 2.3,
    matterDocumentUrl: "/uploads/TTL-2026-084_English_Class8_RSK.pdf",
    receivedDate: "2026-10-22",
    status: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 5,
    titleCode: "TTL-2026-015",
    titleName: "Mathematics - 1",
    localTitleName: "गणित - 1",
    department: "RSK",
    className: "Class 1",
    medium: "Marathi Medium",
    bookType: "Main Textbook",
    innerPages: 76,
    coverPages: 4,
    totalPages: 80,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 160,
    paperArea: 1.5,
    matterDocumentUrl: "/uploads/TTL-2026-015_Maths_Class1_RSK.pdf",
    receivedDate: "2026-09-10",
    status: "Approved",
    academicYear: "2026-2027",
    approvedBy: "MPTBC Tech Officer",
    approvalDate: "2026-09-12",
  },
  {
    id: 6,
    titleCode: "TTL-2026-022",
    titleName: "Science - 2",
    localTitleName: "विज्ञान - 2",
    department: "RSK",
    className: "Class 2",
    medium: "Hindi Medium",
    bookType: "Main Textbook",
    innerPages: 96,
    coverPages: 4,
    totalPages: 100,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 200,
    paperArea: 2.0,
    matterDocumentUrl: "/uploads/TTL-2026-022_Science_Class2_RSK.pdf",
    receivedDate: "2026-09-15",
    status: "Approved",
    academicYear: "2026-2027",
    approvedBy: "MPTBC Tech Officer",
    approvalDate: "2026-09-16",
  },
  {
    id: 7,
    titleCode: "TTL-2026-034",
    titleName: "Social Science - 3",
    localTitleName: "सामाजिक विज्ञान - 3",
    department: "RSK",
    className: "Class 3",
    medium: "English Medium",
    bookType: "Main Textbook",
    innerPages: 108,
    coverPages: 4,
    totalPages: 112,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 230,
    paperArea: 2.2,
    matterDocumentUrl: "/uploads/TTL-2026-034_Social_Class3_RSK.pdf",
    receivedDate: "2026-09-18",
    status: "Approved",
    academicYear: "2026-2027",
    approvedBy: "MPTBC Tech Officer",
    approvalDate: "2026-09-20",
  },
  {
    id: 8,
    titleCode: "TTL-2026-042",
    titleName: "Sanskrit Bharati - 4",
    localTitleName: "संस्कृत भारती - 4",
    department: "RSK",
    className: "Class 4",
    medium: "Urdu Medium",
    bookType: "Main Textbook",
    innerPages: 84,
    coverPages: 4,
    totalPages: 88,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 175,
    paperArea: 1.6,
    matterDocumentUrl: "/uploads/TTL-2026-042_Sanskrit_Class4_RSK.pdf",
    receivedDate: "2026-09-25",
    status: "Hold",
    academicYear: "2026-2027",
  },
];
