export const mockTitleReceivedData: Distribution.TitleReceivedItem[] = [
  {
    id: 101,
    titleCode: "TTL-2026-101",
    titleName: "Textbook / Bhasha Bharati - 1",
    localTitleName: "भाषा भारती - 1",
    department: "RSK",
    className: "Class 1",
    medium: "Hindi Medium",
    bookType: "Main Textbook",
    totalPages: 104,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 200,
    paperArea: 2.0,
    submissionDate: "2026-10-01",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 102,
    titleCode: "TTL-2026-102",
    titleName: "Anandmay Ganit - 1",
    localTitleName: "आनंदमय गणित - 1",
    department: "RSK",
    className: "Class 1",
    medium: "Hindi Medium",
    bookType: "Main Textbook",
    totalPages: 104,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 200,
    paperArea: 2.0,
    submissionDate: "2026-10-05",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 103,
    titleCode: "TTL-2026-103",
    titleName: "English Reader - Class 5",
    localTitleName: "अंग्रेजी रीडर - 5",
    department: "RSK",
    className: "Class 5",
    medium: "English Medium",
    bookType: "Main Textbook",
    totalPages: 120,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 220,
    paperArea: 2.2,
    submissionDate: "2026-09-28",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 104,
    titleCode: "TTL-2026-104",
    titleName: "Physics Part 1 - Class 11",
    localTitleName: "भौतिक विज्ञान - 11",
    department: "CPI",
    className: "Class 11",
    medium: "Hindi Medium",
    bookType: "Main Textbook",
    totalPages: 240,
    innerGsm: "70 GSM",
    coverGsm: "250 GSM",
    weight: 450,
    paperArea: 4.5,
    submissionDate: "2026-10-10",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 105,
    titleCode: "TTL-2026-105",
    titleName: "Higher Secondary Mathematics - 12",
    localTitleName: "उच्चतर गणित - 12",
    department: "CPI",
    className: "Class 12",
    medium: "English Medium",
    bookType: "Main Textbook",
    totalPages: 280,
    innerGsm: "70 GSM",
    coverGsm: "250 GSM",
    weight: 520,
    paperArea: 5.1,
    submissionDate: "2026-10-12",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
  {
    id: 106,
    titleCode: "TTL-2026-106",
    titleName: "Chemistry Workbook - Class 10",
    localTitleName: "रसायन विज्ञान - 10",
    department: "CPI",
    className: "Class 10",
    medium: "Hindi Medium",
    bookType: "Atgrade Workbook",
    totalPages: 160,
    innerGsm: "58 GSM",
    coverGsm: "200 GSM",
    weight: 310,
    paperArea: 3.1,
    submissionDate: "2026-10-14",
    receiptStatus: "Pending",
    academicYear: "2026-2027",
  },
];
