export interface DepotBlockTitleSupplyRow {
  id: string;
  depotCode: string;
  depotName: string;
  blockName: string;
  medium: string;
  classGroup: string;
  bookTitle: string;
  demandQty: number;
  dispatchedQty: number;
  receivedQty: number;
  shortageQty: number;
  damagedQty: number;
  pendingQty: number;
  fulfillmentPct: number;
}

export const depotBlockTitleSupplyData: DepotBlockTitleSupplyRow[] = [
  {
    id: "d1",
    depotCode: "SAGAR",
    depotName: "सागर",
    blockName: "Jabera",
    medium: "Hindi",
    
    classGroup: "Class 3",
    bookTitle: "2026-27 हेतु एफएलएन अभ्यास पुस्तिका (तृतीय चरण)(कक्षा 3)",
    demandQty: 1474,
    dispatchedQty: 1474,
    receivedQty: 1474,
    shortageQty: 0,
    damagedQty: 0,
    pendingQty: 0,
    fulfillmentPct: 100,
  },
  {
    id: "d2",
    depotCode: "SAGAR",
    depotName: "सागर",
    blockName: "Jabera",
    medium: "Hindi",
    classGroup: "Class 7",
    bookTitle: "2026-27 हेतु एटग्रेड अभ्यास पुस्तिका कक्षा 7 (विज्ञान)",
    demandQty: 2100,
    dispatchedQty: 2100,
    receivedQty: 2100,
    shortageQty: 0,
    damagedQty: 0,
    pendingQty: 0,
    fulfillmentPct: 100,
  },
  {
    id: "d3",
    depotCode: "SAGAR",
    depotName: "सागर",
    blockName: "Jabera",
    medium: "English",
    classGroup: "Class 8",
    bookTitle: "2026-27 हेतु एटग्रेड अभ्यास पुस्तिका कक्षा 8 (अंग्रेजी)",
    demandQty: 2218,
    dispatchedQty: 2218,
    receivedQty: 2218,
    shortageQty: 0,
    damagedQty: 0,
    pendingQty: 0,
    fulfillmentPct: 100,
  },
  {
    id: "d4",
    depotCode: "BPL",
    depotName: "भोपाल",
    blockName: "Babai",
    medium: "Hindi",
    classGroup: "Class 3-5",
    bookTitle: "आसपास भाग 3-5",
    demandQty: 1027,
    dispatchedQty: 1027,
    receivedQty: 1027,
    shortageQty: 0,
    damagedQty: 0,
    pendingQty: 0,
    fulfillmentPct: 100,
  },
  {
    id: "d5",
    depotCode: "BPL",
    depotName: "भोपाल",
    blockName: "Babai",
    medium: "Hindi",
    classGroup: "Class 5",
    bookTitle: "गणित का जादू - 5",
    demandQty: 1027,
    dispatchedQty: 1027,
    receivedQty: 1027,
    shortageQty: 0,
    damagedQty: 0,
    pendingQty: 0,
    fulfillmentPct: 100,
  },
  {
    id: "d6",
    depotCode: "BPL",
    depotName: "भोपाल",
    blockName: "Babai",
    medium: "Hindi",
    classGroup: "Class 7",
    bookTitle: "गणित प्रकाश - 7",
    demandQty: 1211,
    dispatchedQty: 1195,
    receivedQty: 1195,
    shortageQty: 16,
    damagedQty: 0,
    pendingQty: 16,
    fulfillmentPct: 98.7,
  },
  {
    id: "d7",
    depotCode: "BPL",
    depotName: "भोपाल",
    blockName: "Babai",
    medium: "Hindi",
    classGroup: "Class 7",
    bookTitle: "जिज्ञासा - 7",
    demandQty: 1211,
    dispatchedQty: 1195,
    receivedQty: 1195,
    shortageQty: 16,
    damagedQty: 0,
    pendingQty: 16,
    fulfillmentPct: 98.7,
  },
  {
    id: "d8",
    depotCode: "GWL",
    depotName: "ग्वालियर",
    blockName: "Dabra",
    medium: "Hindi",
    classGroup: "Class 6",
    bookTitle: "भाषा भारती - 6",
    demandQty: 1425,
    dispatchedQty: 1405,
    receivedQty: 1400,
    shortageQty: 20,
    damagedQty: 5,
    pendingQty: 25,
    fulfillmentPct: 98.2,
  },
  {
    id: "d9",
    depotCode: "GWL",
    depotName: "ग्वालियर",
    blockName: "Dabra",
    medium: "Hindi",
    classGroup: "Class 8",
    bookTitle: "विज्ञान - 8",
    demandQty: 1303,
    dispatchedQty: 1301,
    receivedQty: 1301,
    shortageQty: 2,
    damagedQty: 0,
    pendingQty: 2,
    fulfillmentPct: 99.8,
  },
  {
    id: "d10",
    depotCode: "IND",
    depotName: "इंदौर",
    blockName: "Mhow",
    medium: "English",
    classGroup: "Class 6",
    bookTitle: "English Reader - Class 6",
    demandQty: 1850,
    dispatchedQty: 1500,
    receivedQty: 1480,
    shortageQty: 350,
    damagedQty: 20,
    pendingQty: 370,
    fulfillmentPct: 80.0,
  },
];
