export const mockClasses: Master.ClassItem[] = [
  {
    classId: 1,
    name: "Class 1",
    localName: "कक्षा 1",
    code: "CLS-1",
    isActive: true,
  },
  {
    classId: 2,
    name: "Class 2",
    localName: "कक्षा 2",
    code: "CLS-2",
    isActive: true,
  },
  {
    classId: 3,
    name: "Class 3",
    localName: "कक्षा 3",
    code: "CLS-3",
    isActive: true,
  },
  {
    classId: 4,
    name: "Class 4",
    localName: "कक्षा 4",
    code: "CLS-4",
    isActive: true,
  },
  {
    classId: 5,
    name: "Class 5",
    localName: "कक्षा 5",
    code: "CLS-5",
    isActive: true,
  },
  {
    classId: 6,
    name: "Class 6",
    localName: "कक्षा 6",
    code: "CLS-6",
    isActive: true,
  },
  {
    classId: 7,
    name: "Class 7",
    localName: "कक्षा 7",
    code: "CLS-7",
    isActive: true,
  },
  {
    classId: 8,
    name: "Class 8",
    localName: "कक्षा 8",
    code: "CLS-8",
    isActive: true,
  },
  {
    classId: 9,
    name: "Class 9",
    localName: "कक्षा 9",
    code: "CLS-9",
    isActive: true,
  },
  {
    classId: 10,
    name: "Class 10",
    localName: "कक्षा 10",
    code: "CLS-10",
    isActive: true,
  },
  {
    classId: 11,
    name: "Class 11",
    localName: "कक्षा 11",
    code: "CLS-11",
    isActive: true,
  },
  {
    classId: 12,
    name: "Class 12",
    localName: "कक्षा 12",
    code: "CLS-12",
    isActive: true,
  },
];
