export interface AppendixItem {
  district: string;
  block: string;
  nineTonTrucksRequired: number;
  fourPointFiveTonTrucksRequired: number;
  bundles: number;
}

export const appendixDataIndore: AppendixItem[] = [
  {
    district: "Indore",
    block: "Indore City",
    nineTonTrucksRequired: 24,
    fourPointFiveTonTrucksRequired: 4,
    bundles: 124,
  },
  {
    district: "Indore",
    block: "Mhow",
    nineTonTrucksRequired: 10,
    fourPointFiveTonTrucksRequired: 3,
    bundles: 62,
  },
  {
    district: "Indore",
    block: "Sanwer",
    nineTonTrucksRequired: 7,
    fourPointFiveTonTrucksRequired: 1,
    bundles: 55,
  },
];

export const mockWorkOrders: Transportation.WorkOrder[] = [
  // ===== DELIVERED (7) — ON SCHEDULE in grid =====

  {
    workOrderId: "WO-IND-001",
    district: "Indore",
    block: "Indore City",
    totalBundles: 120,
    allocatedTransporterId: 3,
    transporterName: "Verma Logistics",
    instructionDate: "2026-08-10",
    dueDate: "2026-08-15",
    status: "Delivered",
    nineTonTrucksRequired: 20,
    fourPointFiveTonTrucksRequired: 5,
    dispatches: [
      {
        dispatchId: "DISP-101",
        workOrderId: "WO-IND-001",
        truckNo: "MP-09-AB-1234",
        driverName: "Ramesh Singh",
        driverMobile: "9876543210",
        capacity: 9,
        bundlesLoaded: 120,
        dispatchDate: "2026-08-10",
        status: "Delivered",
        lrNumber: "LR-9011",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_101.pdf",
        podSubmittedAt: "2026-08-14 10:00",
        actualDeliveryDate: "2026-08-14",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-IND-002",
    district: "Indore",
    block: "Mhow",
    totalBundles: 60,
    allocatedTransporterId: 3,
    transporterName: "Verma Logistics",
    instructionDate: "2026-08-11",
    dueDate: "2026-08-16",
    status: "Delivered",
    nineTonTrucksRequired: 10,
    fourPointFiveTonTrucksRequired: 2,
    dispatches: [
      {
        dispatchId: "DISP-102",
        workOrderId: "WO-IND-002",
        truckNo: "MP-09-CD-5678",
        driverName: "Sanjay Kumar",
        driverMobile: "9988776655",
        capacity: 4.5,
        bundlesLoaded: 60,
        dispatchDate: "2026-08-11",
        status: "Delivered",
        lrNumber: "LR-9012",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_102.pdf",
        podSubmittedAt: "2026-08-15 14:30",
        actualDeliveryDate: "2026-08-15",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-IND-003",
    district: "Indore",
    block: "Sanwer",
    totalBundles: 80,
    allocatedTransporterId: 3,
    transporterName: "Verma Logistics",
    instructionDate: "2026-08-11",
    dueDate: "2026-08-16",
    status: "Delivered",
    nineTonTrucksRequired: 8,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-103",
        workOrderId: "WO-IND-003",
        truckNo: "MP-09-EF-9012",
        driverName: "Vikram Dev",
        driverMobile: "9123456789",
        capacity: 4.5,
        bundlesLoaded: 80,
        dispatchDate: "2026-08-11",
        status: "Delivered",
        lrNumber: "LR-9013",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_103.pdf",
        podSubmittedAt: "2026-08-15 16:00",
        actualDeliveryDate: "2026-08-15",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-BHO-001",
    district: "Bhopal",
    block: "Phanda",
    totalBundles: 120,
    allocatedTransporterId: 3,
    transporterName: "Verma Logistics",
    instructionDate: "2026-08-12",
    dueDate: "2026-08-17",
    status: "Delivered",
    nineTonTrucksRequired: 12,
    fourPointFiveTonTrucksRequired: 2,
    dispatches: [
      {
        dispatchId: "DISP-201",
        workOrderId: "WO-BHO-001",
        truckNo: "MP-04-HE-7777",
        driverName: "Kailash Gehlot",
        driverMobile: "9000011111",
        capacity: 9,
        bundlesLoaded: 120,
        dispatchDate: "2026-08-12",
        status: "Delivered",
        lrNumber: "LR-9021",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_201.pdf",
        podSubmittedAt: "2026-08-16 11:00",
        actualDeliveryDate: "2026-08-16",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-UJJ-001",
    district: "Ujjain",
    block: "Ghattia",
    totalBundles: 90,
    allocatedTransporterId: 4,
    transporterName: "Sharma Transport",
    instructionDate: "2026-08-13",
    dueDate: "2026-08-18",
    status: "Delivered",
    nineTonTrucksRequired: 10,
    fourPointFiveTonTrucksRequired: 0,
    dispatches: [
      {
        dispatchId: "DISP-301",
        workOrderId: "WO-UJJ-001",
        truckNo: "MP-13-GA-8888",
        driverName: "Dinesh Rathore",
        driverMobile: "9111122222",
        capacity: 9,
        bundlesLoaded: 90,
        dispatchDate: "2026-08-13",
        status: "Delivered",
        lrNumber: "LR-9031",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_301.pdf",
        podSubmittedAt: "2026-08-17 09:30",
        actualDeliveryDate: "2026-08-17",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-JAB-002",
    district: "Jabalpur",
    block: "Katni",
    totalBundles: 75,
    allocatedTransporterId: 5,
    transporterName: "Patel Roadways",
    instructionDate: "2026-08-11",
    dueDate: "2026-08-16",
    status: "Delivered",
    nineTonTrucksRequired: 8,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-402",
        workOrderId: "WO-JAB-002",
        truckNo: "MP-20-QR-3344",
        driverName: "Mohan Lal",
        driverMobile: "9333344455",
        capacity: 9,
        bundlesLoaded: 75,
        dispatchDate: "2026-08-11",
        status: "Delivered",
        lrNumber: "LR-9042",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_402.pdf",
        podSubmittedAt: "2026-08-15 13:00",
        actualDeliveryDate: "2026-08-15",
        deliveryDelayDays: 0,
      },
    ],
  },

  {
    workOrderId: "WO-GWA-002",
    district: "Gwalior",
    block: "Gwalior City",
    totalBundles: 95,
    allocatedTransporterId: 6,
    transporterName: "MP Roadlines",
    instructionDate: "2026-08-12",
    dueDate: "2026-08-17",
    status: "Delivered",
    nineTonTrucksRequired: 10,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-502",
        workOrderId: "WO-GWA-002",
        truckNo: "MP-07-GC-1111",
        driverName: "Suresh Mishra",
        driverMobile: "9555566666",
        capacity: 9,
        bundlesLoaded: 95,
        dispatchDate: "2026-08-12",
        status: "Delivered",
        lrNumber: "LR-9052",
        podUploaded: true,
        podFilePath: "mock_uploads/pod_502.pdf",
        podSubmittedAt: "2026-08-16 15:00",
        actualDeliveryDate: "2026-08-16",
        deliveryDelayDays: 0,
      },
    ],
  },

  // ===== IN TRANSIT (3) — recent dispatch dates, on time =====

  {
    workOrderId: "WO-JAB-001",
    district: "Jabalpur",
    block: "Sihora",
    totalBundles: 100,
    allocatedTransporterId: 5,
    transporterName: "Patel Roadways",
    instructionDate: "2026-08-17",
    dueDate: "2026-08-22",
    status: "In Transit",
    nineTonTrucksRequired: 11,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-401",
        workOrderId: "WO-JAB-001",
        truckNo: "MP-20-PA-9999",
        driverName: "Sohan Lal",
        driverMobile: "9222233333",
        capacity: 9,
        bundlesLoaded: 85,
        dispatchDate: "2026-08-18",
        status: "In Transit",
        lrNumber: "LR-9041",
        lat: 23.4841,
        lng: 80.1102,
        podUploaded: false,
      },
    ],
  },

  {
    workOrderId: "WO-GWA-001",
    district: "Gwalior",
    block: "Dabra",
    totalBundles: 85,
    allocatedTransporterId: 6,
    transporterName: "MP Roadlines",
    instructionDate: "2026-08-16",
    dueDate: "2026-08-21",
    status: "In Transit",
    nineTonTrucksRequired: 9,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-501",
        workOrderId: "WO-GWA-001",
        truckNo: "MP-07-TR-6666",
        driverName: "Devendra Singh",
        driverMobile: "9444455555",
        capacity: 9,
        bundlesLoaded: 80,
        dispatchDate: "2026-08-17",
        status: "In Transit",
        lrNumber: "LR-9051",
        lat: 25.8943,
        lng: 78.4355,
        podUploaded: false,
      },
    ],
  },

  {
    workOrderId: "WO-RWA-001",
    district: "Rewa",
    block: "Rewa City",
    totalBundles: 70,
    allocatedTransporterId: 4,
    transporterName: "Sharma Transport",
    instructionDate: "2026-08-17",
    dueDate: "2026-08-22",
    status: "In Transit",
    nineTonTrucksRequired: 7,
    fourPointFiveTonTrucksRequired: 1,
    dispatches: [
      {
        dispatchId: "DISP-601",
        workOrderId: "WO-RWA-001",
        truckNo: "MP-18-RW-2233",
        driverName: "Pradeep Tiwari",
        driverMobile: "9777788888",
        capacity: 9,
        bundlesLoaded: 65,
        dispatchDate: "2026-08-18",
        status: "In Transit",
        lrNumber: "LR-9061",
        lat: 24.5335,
        lng: 81.3043,
        podUploaded: false,
      },
    ],
  },

  // ===== PENDING DISPATCH (1) — no dispatches yet =====

  {
    workOrderId: "WO-SEH-001",
    district: "Bhopal",
    block: "Sehore",
    totalBundles: 65,
    allocatedTransporterId: 3,
    transporterName: "Verma Logistics",
    instructionDate: "2026-08-19",
    dueDate: "2026-08-24",
    status: "Pending Dispatch",
    nineTonTrucksRequired: 7,
    fourPointFiveTonTrucksRequired: 0,
    dispatches: [],
  },
];
