export const mockGsmPaperDemandData: Paper.GsmPaperDemandItem[] = [
  {
    id: 1,
    gsmCode: "GSM-58-REEL",
    gsmName: "58 GSM Maplitho Reel Paper",
    gsmValue: 58,
    paperCategory: "Reel Paper (Inner)",
    usageType: "Textbook Inner Pages (Class 1 to 8 & Workbooks)",
    titlesCount: 14,
    totalBooksCount: 4250000,
    netDemandMt: 420,
    wastagePercent: 5,
    grossDemandMt: 441,
    estPricePerMt: 68000,
    totalBudgetLakhs: 300,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 2,
    gsmCode: "GSM-70-REEL",
    gsmName: "70 GSM Maplitho Reel Paper",
    gsmValue: 70,
    paperCategory: "Reel Paper (Inner)",
    usageType: "Textbook Inner Pages (Class 9 to 12 & High School)",
    titlesCount: 12,
    totalBooksCount: 3100000,
    netDemandMt: 385,
    wastagePercent: 5,
    grossDemandMt: 404,
    estPricePerMt: 72000,
    totalBudgetLakhs: 291,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 3,
    gsmCode: "GSM-200-SHEET",
    gsmName: "200 GSM Art Card Sheet Paper",
    gsmValue: 200,
    paperCategory: "Sheet Paper (Cover)",
    usageType: "Textbook Cover Pages (Class 1 to 8)",
    titlesCount: 14,
    totalBooksCount: 4250000,
    netDemandMt: 126,
    wastagePercent: 3,
    grossDemandMt: 130,
    estPricePerMt: 85000,
    totalBudgetLakhs: 110,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 4,
    gsmCode: "GSM-250-SHEET",
    gsmName: "250 GSM Art Card Sheet Paper",
    gsmValue: 250,
    paperCategory: "Sheet Paper (Cover)",
    usageType: "Textbook Cover Pages (Class 9 to 12)",
    titlesCount: 12,
    totalBooksCount: 3100000,
    netDemandMt: 145,
    wastagePercent: 3,
    grossDemandMt: 150,
    estPricePerMt: 90000,
    totalBudgetLakhs: 135,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 5,
    gsmCode: "GSM-80-REEL",
    gsmName: "80 GSM High-Grade Maplitho Reel Paper",
    gsmValue: 80,
    paperCategory: "Reel Paper (Inner)",
    usageType: "Teacher Guides & Supplementary Workbooks",
    titlesCount: 8,
    totalBooksCount: 950000,
    netDemandMt: 115,
    wastagePercent: 5,
    grossDemandMt: 121,
    estPricePerMt: 76000,
    totalBudgetLakhs: 92,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 6,
    gsmCode: "GSM-220-SHEET",
    gsmName: "220 GSM Coated Art Paper Sheet",
    gsmValue: 220,
    paperCategory: "Sheet Paper (Cover)",
    usageType: "Vocational & Technical Course Covers",
    titlesCount: 6,
    totalBooksCount: 650000,
    netDemandMt: 33,
    wastagePercent: 3,
    grossDemandMt: 34,
    estPricePerMt: 88000,
    totalBudgetLakhs: 30,
    status: "Draft",
    academicYear: "2026-2027",
  },
  {
    id: 7,
    gsmCode: "GSM-300-SHEET",
    gsmName: "300 GSM Heavy Board Sheet Paper",
    gsmValue: 300,
    paperCategory: "Sheet Paper (Cover)",
    usageType: "Special Reference & Atlas Cover Hardboard",
    titlesCount: 4,
    totalBooksCount: 400000,
    netDemandMt: 28,
    wastagePercent: 3,
    grossDemandMt: 29,
    estPricePerMt: 95000,
    totalBudgetLakhs: 27,
    status: "Draft",
    academicYear: "2026-2027",
  },
];
