declare namespace Permission {
  // Features mapped to backend policies
  type Feature =
    | "@master/office-level"
    | "@master/office"
    | "@master/office-type"
    | "@master/anganwadi-type"
    | "@master/awc-service"
    | "@child-directory/age-group"
    | "@child-directory/scheme"
    | "@child-directory/health-issue"
    | "@child-directory/immunization-status"
    | "@master/state"
    | "@anganwadi/center-registration"
    | "@anganwadi/infrastructure"
    | "@user-management/role-permissions"
    | "@user-management/user-assignment"
    | "@user-management/users"
    | "@user-management/roles"
    | "@master/division"
    | "@master/district"
    | "@master/caste"
    | "@master/religion"
    | "@master/blood-group"
    | "@master/nationality"
    | "@master/project"
    | "@master/sector"
    | "@master/designation"
    | "@master/agency"
    | "@master/located-place"
    | "@master/marital-status"
    | "@master/designation-type"
    | "@master/drinking-water-source"
    | "@master/connectivity-status"
    | "@master/building-status"
    | "@master/area-type"
    | "@master/anganwadi-building"
    | "@master/disability-type"
    | "@master/disability-percentage"
    | "@master/qualification-type"
    | "@master/qualification"
    | "@master/qualification-subject"
    | "@master/bank"
    | "@master/ifsc-code"
    | "@anganwadi/staff-type"
    | "@anganwadi/infrastructure"
    | "@anganwadi/staff"
    | "@master/class"
    | "@master/book-type"
    | "@master/medium"
    | "@master/gsm"
    | "@master/title"
    | "@master/block"
    | "@master/sub-depot"
    | "@master/depot"
    | "@master/book-paper-requirement"
    // HRMS
    | "@hrms/employee-details"
    // Distribution
    | "@distribution/department-demand"
    | "@distribution/dashboard"
    | "@distribution/demand-approval";
  // Actions mapped to backend policies
  type Action = "read" | "write";
}
