export const initialBlockList: Master.BlockItem[] = [
  {
    blockId: 1,
    name: "ALIRAJPUR",
    localName: "अलीराजपुर",
    code: "BLK-2349-01",
    districtId: 1,
    districtName: "Alirajpur",
    divisionId: 1,
    divisionName: "Indore",
    isActive: true,
  },
  {
    blockId: 2,
    name: "CHANDRA SHEKHAR AZAD NAGAR",
    localName: "चंद्रशेखर आजाद नगर",
    code: "BLK-2349-02",
    districtId: 1,
    districtName: "Alirajpur",
    divisionId: 1,
    divisionName: "Indore",
    isActive: true,
  },
  {
    blockId: 3,
    name: "JOBAT",
    localName: "जोबट",
    code: "BLK-2349-03",
    districtId: 1,
    districtName: "Alirajpur",
    divisionId: 1,
    divisionName: "Indore",
    isActive: true,
  },
  {
    blockId: 4,
    name: "PHANDA",
    localName: "फंदा",
    code: "BLK-2350-01",
    districtId: 2,
    districtName: "Bhopal",
    divisionId: 2,
    divisionName: "Bhopal",
    isActive: true,
  },
  {
    blockId: 5,
    name: "BERASIA",
    localName: "बैरसिया",
    code: "BLK-2350-02",
    districtId: 2,
    districtName: "Bhopal",
    divisionId: 2,
    divisionName: "Bhopal",
    isActive: true,
  },
];
