import { USER_ROLES } from "./authTypes";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [USER_ROLES.TBC_HEAD_OFFICE]: [
    "dashboard",
    "profile",
    "master",
    "user-management",
    "hrms",
    "printer-section",
    "depot-section",
    "distribution-section",
    "paper-section",
    "reports",
    "transport",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // User Management
    "user-management/user",
    "user-management/role",
    "user-management/user-assignment",
    "user-management/role-permissions",
    // HRMS
    "hrms/employee-details",
    // Title Section
    "title-section/title-received",
    "title-section/title-approval",
    "title-section/title-master",
    // Printer Section
    "printer-section/printer-registration",
    "printer-orders",
    "pending-printer-orders",
    "printer-supply",
    // Depot Section
    "depot-section/depot-registration",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/demand-approval",
    "paper-distribution",
    "distribution-history",
    // Paper Section
    "paper-section/book-paper-requirement",
    "paper-section/gsm-demand-report",
    "paper-stock",
    "central-paper-receiving",
    "stock-transactions",
    "stock-ledger",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
    // Dashboard (TBC Head Office specific)
    "central-dashboard",
  ],

  [USER_ROLES.DISTRICT_DEPOT]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Printer Section
    "printer-section/printer-registration",
    "printer-orders",
    "pending-printer-orders",
    "assigned-demand",
    // HRMS
    "hrms/employee-details",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/demand-approval",
    "paper-distribution",
    "distribution-history",
    // District Depot
    "district-depot/printer-assigned-demand",
    "district-depot/challan-received",
    "district-depot/challan-to-block",
    "district-depot/dispatch-history",
    // Transport / Depot Transport
    "transport",
    "depot-transport/transport-orders",
    "depot-transport/vehicle-management",
    "depot-transport/fuel-log",
  ],

  [USER_ROLES.CENTRAL_DEPOT]: [
    "dashboard",
    "profile",
    "central-dashboard",
    // Printer Section
    "printer-section/printer-registration",
    "printer-orders",
    "pending-printer-orders",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/demand-approval",
    "paper-distribution",
    "distribution-history",
    // Paper Section
    "paper-section/book-paper-requirement",
    "paper-section/gsm-demand-report",
    "paper-stock",
    "central-paper-receiving",
    "stock-transactions",
    "stock-ledger",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
    // Printer Supply
    "printer-supply",
  ],

  [USER_ROLES.PRINTER]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Printer Section
    "printer-section/printer-registration",
    "printer-orders",
    "pending-printer-orders",
    // Printer Specific
    "tender",
    "paper-receiving",
    "supply-section",
    // Depot Section
    "depot-section/depot-registration",
    "payment",
  ],

  [USER_ROLES.PAPER_VENDOR]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Paper Vendor Specific
    "paper-supply",
    "paper-orders",
    "paper-receiving",
    "payment",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
  ],

  [USER_ROLES.DISTRIBUTION_SECTION]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Title Section
    "title-section/title-received",
    "title-section/title-approval",
    "title-section/title-master",
    // Distribution Section Specific
    "demand",
    "allocation",
    "distribution",
    "dispatch",
    "distribution-tracking",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
  ],
};
