import { USER_ROLES } from "./authTypes";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [USER_ROLES.TBC_HEAD_OFFICE]: [
    "dashboard",
    "profile",
    "master",
    "user-management",
    "hrms",
    "finance",
    "finance/dashboard",
    "grievance",
    "grievance/dashboard",
    "legal",
    "legal/dashboard",
    "printer-section",
    "depot-section",
    "distribution-section",
    "paper-section",
    "reports",
    "reports/depot-block-title-supply",
    "reports/depot-supply-status",
    "reports/agency-demand",
    "transport",
    "transportation",
    "transport/tender-details",
    "transport/work-order",
    "transport/dispatch",
    "transport/tracking",
    "transport/pod",
    "transport/billing",
    "transport/disbursement",
    "transport/reports",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // User Management
    "user-management/user",
    "user-management/role",
    "user-management/user-assignment",
    "user-management/role-permissions",
    // HRMS
    "hrms/employee-details",
    // Title Section
    "title-section/title-received",
    "title-section/title-approval",
    "title-section/title-master",
    // Printer Section
    "printer-section/dashboard",
    "printer-section/printer-registration",
    "printer-section/quality-inspection",
    "printer-orders",
    "pending-printer-orders",
    "printer-supply",
    // Depot Section
    "depot-section/central-depot-dashboard",
    "depot-section/depot-registration",
    "district-depot/depot-to-depot",
    "district-depot/opening-stock",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/depot-demand-distribution",
    "distribution-section/demand-approval",
    "distribution-section/printer-demand-mapping",
    "paper-distribution",
    "distribution-history",
    "paper-issue-to-printer",
    // Paper Section
    "paper-section/book-paper-requirement",
    "paper-section/gsm-demand-report",
    "paper-stock",
    "central-paper-receiving",
    "stock-transactions",
    "stock-ledger",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
    // Dashboard (TBC Head Office specific)
    "central-dashboard",
    // District Depot / Transport Section
    "assigned-demand",
    "district-depot/printer-assigned-demand",
    "district-depot/challan-received",
    "district-depot/challan-to-block",
    "district-depot/dispatch-history",
    "depot-transport/transport-orders",
    "depot-transport/vehicle-management",
    "depot-transport/fuel-log",
    // Printer / Paper Vendor Specific
    "tender",
    "paper-receiving",
    "supply-section",
    "payment",
    "paper-supply",
    "paper-orders",
    // Distribution Section Specific
    "demand",
    "allocation",
    // Paper Section - additional pages
    "paper-section/paper-tender",
    "paper-section/paper-vendor-profile",
    "paper-section/paper-order-allocation",
    "paper-section/lab-testing",
    // District Depot Transport (parent key)
    "depot-transport",
    // Standalone pages
    "distribution",
    "dispatch",
    "distribution-tracking",
    "title-master",
    "gsm-master",
  ],

  [USER_ROLES.TRANSPORTER]: [
    "dashboard",
    "profile",
    "transport",
    "transportation",
    "transport/tender-details",
    "transport/work-order",
    "transport/dispatch",
    "transport/tracking",
    "transport/pod",
    "transport/billing",
    "transport/disbursement",
    "transport/reports",
  ],

  [USER_ROLES.DISTRICT_DEPOT]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Printer Section
    "printer-section/printer-registration",
    "printer-section/quality-inspection",
    "printer-orders",
    "pending-printer-orders",
    "assigned-demand",
    // HRMS
    "hrms/employee-details",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/depot-demand-distribution",
    "distribution-section/demand-approval",
    "paper-distribution",
    "distribution-history",
    "paper-issue-to-printer",
    // District Depot
    "district-depot/printer-assigned-demand",
    "district-depot/challan-received",
    "district-depot/challan-to-block",
    "district-depot/dispatch-history",
    // Transport / Depot Transport
    "transport",
    "transportation",
    "transport/tender-details",
    "transport/work-order",
    "transport/dispatch",
    "transport/tracking",
    "transport/pod",
    "transport/billing",
    "transport/disbursement",
    "transport/reports",
    "depot-transport/transport-orders",
    "depot-transport/vehicle-management",
    "depot-transport/fuel-log",
  ],

  [USER_ROLES.CENTRAL_DEPOT]: [
    "dashboard",
    "profile",
    "central-dashboard",
    // Transportation
    "transport",
    "transportation",
    "transport/tender-details",
    "transport/work-order",
    "transport/dispatch",
    "transport/tracking",
    "transport/pod",
    "transport/billing",
    "transport/disbursement",
    "transport/reports",
    // Printer Section
    "printer-orders",
    "pending-printer-orders",
    // Depot Section
    "depot-section/central-depot-dashboard",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/depot-demand-distribution",
    "distribution-section/demand-approval",
    "paper-distribution",
    "distribution-history",
    "paper-issue-to-printer",
    // Paper Section
    "paper-section/book-paper-requirement",
    "paper-section/gsm-demand-report",
    "paper-stock",
    "central-paper-receiving",
    "stock-transactions",
    "stock-ledger",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
    // Printer Supply
    "printer-supply",
  ],

  [USER_ROLES.PRINTER]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Printer Section
    "printer-section/dashboard",
    "printer-section/printer-registration",
    "printer-section/quality-inspection",
    "printer-orders",
    "pending-printer-orders",
    // Printer Specific
    "tender",
    "paper-receiving",
    "supply-section",
    // Depot Section
    "depot-section/depot-registration",
    "payment",
  ],

  [USER_ROLES.PAPER_VENDOR]: [
    "dashboard",
    "profile",
    "paper-section",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Paper Section
    "paper-section/book-paper-requirement",
    "paper-section/gsm-demand-report",
    "paper-stock",
    "central-paper-receiving",
    "stock-transactions",
    "stock-ledger",
    // Paper Vendor Specific
    "paper-supply",
    "paper-orders",
    "paper-receiving",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
  ],

  [USER_ROLES.DISTRIBUTION_SECTION]: [
    "dashboard",
    "profile",
    // Master Config
    "master/office-level",
    "master/office-type",
    "master/office",
    "master/state",
    "master/division",
    "master/district",
    "master/block",
    "master/depot",
    "master/sub-depot",
    "master/caste",
    "master/religion",
    "master/blood-group",
    "master/nationality",
    "master/designation",
    "master/designation-type",
    "master/qualification",
    "master/qualification-type",
    "master/qualification-subject",
    "master/class",
    "master/book-type",
    "master/medium",
    "master/gsm",
    // Title Section
    "title-section/title-received",
    "title-section/title-approval",
    "title-section/title-master",
    // Distribution Section
    "distribution-section/department-demand",
    "distribution-section/dashboard",
    "distribution-section/depot-demand-distribution",
    "distribution-section/demand-approval",
    "distribution-section/printer-demand-mapping",
    "paper-distribution",
    "distribution-history",
    "paper-issue-to-printer",
    // Distribution Section Specific
    // "demand",
    // "allocation",
    // Reports
    "reports/depot-supply-status",
    "reports/agency-demand",
    "gsm-stock-report",
    "printer-order-report",
    "printer-supply-report",
    "paper-distribution-report",
  ],
};
